export const ATTR_POSITION = 'a_position'
export const ATTR_COLOR = 'a_color'
export const ATTR_TEXCOORD = 'a_tex_coord'
export const ATTR_ALPHA = 'a_alpha'

export const UNI_ORTH = 'u_orth'
export const UNI_TRANSFORM = 'u_transform'
export const UNI_SAMPLER = 'u_sampler'
export const UNI_ALPHA = 'u_alpha'
export const UNI_CIRCLE = 'u_circle'
export const UNI_COLOR = 'u_color'
export const UNI_BRIGHTNESS = 'u_brightness'